name: Test destructive mode
on:
  push:
    branches:
      - "track/*"
      - "main"
  pull_request:
    branches:
      - "track/*"
      - "main"

jobs:
  build:
    name: Release to edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branches
        run: git branch

      - name: Check libraries
        uses: ./charming-actions/check-libraries
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: ./charming-actions/channel
        id: channel

      - name: Upload charm to charmhub
        uses: ./charming-actions/upload-charm
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "${{ steps.channel.outputs.name }}"
          charm-path: ./
